version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: bada-bazaar
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./application.properties:/app/application.properties
